# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "89ec580619d25a97bffda5c0e5bcd8e1"
name = "MontyPay"
handle = "montypay-5"
application_url = "https://shopify.dev/apps/default-app-home"
embedded = false

[build]
automatically_update_urls_on_dev = false
dev_store_url = "monty-pay-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://shopify-app-sng2.onrender.com/auth/callback",
  "https://shopify-app-sng2.onrender.com/auth/shopify/callback",
  "https://shopify-app-sng2.onrender.com/api/auth/callback"
]

[webhooks]
api_version = "2024-10"

[pos]
embedded = false
