# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b994045fe32b81c8c974ddce386eb52e"
name = "MontyPay Payment"
handle = "montypay-payment"
application_url = "https://charger-contrary-hat-vendor.trycloudflare.com"
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = "montypay-payment-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://charger-contrary-hat-vendor.trycloudflare.com/auth/callback",
  "https://charger-contrary-hat-vendor.trycloudflare.com/auth/shopify/callback",
  "https://charger-contrary-hat-vendor.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
