# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "49561972d45175963e896c5502b18e1c"
name = "Montypay Payment"
handle = "montypay-payment"
application_url = "https://physical-presentation-stevens-turtle.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "montypay-payment-dev.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = ""

[auth]
redirect_urls = [
  "https://physical-presentation-stevens-turtle.trycloudflare.com/auth/callback",
  "https://physical-presentation-stevens-turtle.trycloudflare.com/auth/shopify/callback",
  "https://physical-presentation-stevens-turtle.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

[pos]
embedded = false
